#!/usr/bin/env bash

# THIS IS SXHKD CONFIG FILE

#----------------#
#  APPLICATIONS  |
#----------------#

# TERMINAL EMULATOR
super + Return
	termite

# PROGRAM LAUNCHER
super + d
	dmenu_run -nb "#101411" -sb "#9c978c" -fn "Monospace-10" -p "Command" -l 16

# RELOAD SXHKD
super + Escape
	pkill -USR1 -x sxhkd

# TAKE A SCREENSHOT
Print
	scrot

#------------------#
#  VOLUME CONTROL  |
#------------------#

ctrl + alt + j
	amixer sset Master 1%-

ctrl + alt + k
	amixer sset Master 1%+

ctrl + alt + m
	amixer sset Master toggle

#----------------------#
#  BRIGHTNESS CONTROL  |
#----------------------#

ctrl + alt + h
	xbacklight -1

ctrl + alt + l
	xbacklight +1

#-----------------#
#  BSPWM HOTKEYS  |
#-----------------#

# RESTART BSPWM
super + ctrl + r
	bspc wm -r

# LOGOUT
super + ctrl + q
	bspc quit

# CLOSE AND KILL
super + {_,shift + }q
	bspc node -{c,k}

# TOGGLE MONOCLE LAYOUT
super + m
	bspc desktop -l next

# SWAP THE CURRENT NODE AND THE BIGGEST NODE
super + g
	bspc node -s biggest

# HIDE THE CURRENT NODE
super + v
	bspc node -g hidden

super + shift + v
	bspc node {,$(bspc query -N -n .hidden | tail -n1)} -g hidden=off

#---------#
#  STATE  |
#---------#

# CHANGE THE WINDOW STATE
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

#--------------#
#  FOCUS/MOVE  |
#--------------#

# FOCUS/MOVE THE NODE
super + {_,shift + }{h,j,k,l}
	bspc node -{f,n} {west,south,north,east}

# FOCUS THE NEXT/PREVIOUS NODE IN THE CURRENT DESKTOP
alt + {_,shift + }Tab
	bspc node -f {next,prev}.local

# FOCUS THE NEXT/PREVIOUS DESKTOP IN THE CURRENT MONITOR
super + {Left,Right}
	bspc desktop -f {prev,next}.local

# FOCUS THE LAST NODE/DESKTOP
super + {grave,Tab}
	bspc {node,desktop} -f last

# FOCUS THE OLDER OR NEWER NODE IN THE FOCUS HISTORY
super + {i,o}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# FOCUS OR SEND TO THE GIVEN DESKTOP
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#-------------#
#  PRESELECT  |
#-------------#

# PRESELECT THE DIRECTION
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# PRESELECT THE RATIO
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# CANCEL THE PRESELECTION FOR THE FOCUSED NODE
super + ctrl + space
	bspc node -p cancel

# CANCEL THE PRESELECTION FOR THE FOCUSED DESKTOP
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#----------#
#  RESIZE  |
#----------#

# EXPAND A WINDOW
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# CONTRACT A WINDOW
super + alt + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

