#! /bin/sh

# THIS IS BSPWM CONFIG FILE

#------------------#
#  BSPWM SETTINGS  |
#------------------#

# MONITOR
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# BORDER
bspc config border_width 4
bspc config focused_border_color \#D93735
bspc config normal_border_color \#E2D9C8

# WINDOW
bspc config window_gap 36
bspc config focus_follows_pointer true
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# RULE
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#-------------#
#  AUTOSTART  |
#-------------#

# POLKIT
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

# HOTKEY
sxhkd &

# PANEL
tint2 &
nm-applet &
fcitx &

# COMPOSITOR
picom &

# WALLPAPER
wal -R &

