#! /bin/sh

# THIS IS BSPWM CONFIG FILE

#------------------#
#  BSPWM SETTINGS  |
#------------------#

# MONITOR
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# BORDER
bspc config border_width 2
bspc config focused_border_color \#b84246
bspc config normal_border_color \#ccd7e1

# PRESELECT
bspc config presel_feedback_color \#b84246

# WINDOW
bspc config window_gap 24
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# RULE
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#------------#
#  XSETROOT  |
#------------#

# CURSOR
xsetroot -cursor_name left_ptr

#-------------#
#  AUTOSTART  |
#-------------#

# POLKIT
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

# HOTKEY
sxhkd &

# PANEL
tint2 &
nm-applet &
fcitx &

# COMPOSITOR
picom &

# WALLPAPER
wal -i /usr/share/backgrounds/alter-nochr.png &

