#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 4
bspc config focused_border_color \#D93735
bspc config normal_border_color \#E2D9C8
bspc config window_gap 36
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

tint2 &
nm-applet &
fcitx &
picom &
nitrogen --restore &
